export enum WS_NOTIFICATION_EVENTS{
    JOIN_SERVER = 'JOIN_SERVER',
    NEW_USER = 'NEW_USER',
    JOIN_ROOM = 'JOIN_ROOM',
    DISCONNECT = 'DISCONNECT',
    UNSENT = 'UNSENT',
    NEW_NOTIFICATION = 'NEW_NOTIFICATION',
    UPDATED = 'UPDATED',
    CHANGED = 'CHANGED',
    EMPTY = 'EMPTY',
    DONE = 'DONE',
    DELETED = 'DELETED',
}

export const CLIENT_URI = "http://localhost:3000";